### ISSUE TITLE
New version of paybox

### ISSUE THREAD

**Issue by aibekdv** [urmatt/flutter_paybox#1]
**[Flutter_paybox](https://pub.dev/packages/flutter_paybox)** пакетинин жаңы версиясы качан чыгат?

Биздин проектте **[dio](https://pub.dev/packages/dio)** пакетинин версиясы жогору болгондугуна байланыштуу flutter_paybox пакетин кошууда көйгөй жаралып жатат?

**Comment by aibekdv** [comment]
@urmatt Мени кошсоңуз мен өзүм эле жаңы версиясын чыгарып берейин.

**Comment by urmatt** [comment]
Жаңылап жатам. Аз убакытта чыгат.
